[package]
name = "rusty_gallows"
version = "0.1.0"
authors = ["sumedh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3"
rand = "0.7"